 version: "3"

 services:
  master:
    build: .
    image: sparky/spark_image
    container_name: master
    ports:
      - 4040:4040
      - 7077:7077
      - 8080:8080
      - 6066:6066
    command: ["home/radone/sparky", "--configuration=home/radone/sparky/master.conf"]
 
#---------------------------------------
# SLAVE CONFIGURATION 
#---------------------------------------
  slave:
    image: sparky/spark_image
    depends_on:
      - master
    ports:
      - 8081:8081
    command: ["home/radone/sparky", "--configuration=home/radone/sparky/slave.conf"]
    volumes:
        - ./docker-volume/spark-output/:/opt/output
        - ./docker-volume/spark-events/:/opt/spark-events

#---------------------------------------
# HISTORY SERVER CONFIGURATION 
#---------------------------------------
  history-server:
      image: sparky/spark_image
      container_name: history-server
      depends_on:
        - master
      ports:
        - 18080:18080
      command: ["home/radone/sparky", "--configuration=home/radone/sparky/history-server.conf"]
      volumes:
        - ./docker-volume/sparky